// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataxService.proto

package com.wallfacers.data.platform.stub.service.datax;

public final class DataxServiceBuilder {
  private DataxServiceBuilder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RunRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DataxServiceProto.RunRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 任务id
     * </pre>
     *
     * <code>int64 jobId = 1;</code>
     * @return The jobId.
     */
    long getJobId();

    /**
     * <pre>
     * 执行代码
     * </pre>
     *
     * <code>string code = 2;</code>
     * @return The code.
     */
    java.lang.String getCode();
    /**
     * <pre>
     * 执行代码
     * </pre>
     *
     * <code>string code = 2;</code>
     * @return The bytes for code.
     */
    com.google.protobuf.ByteString
        getCodeBytes();
  }
  /**
   * Protobuf type {@code DataxServiceProto.RunRequest}
   */
  public static final class RunRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DataxServiceProto.RunRequest)
      RunRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RunRequest.newBuilder() to construct.
    private RunRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RunRequest() {
      code_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RunRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RunRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              jobId_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              code_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.internal_static_DataxServiceProto_RunRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.internal_static_DataxServiceProto_RunRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest.class, com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest.Builder.class);
    }

    public static final int JOBID_FIELD_NUMBER = 1;
    private long jobId_;
    /**
     * <pre>
     * 任务id
     * </pre>
     *
     * <code>int64 jobId = 1;</code>
     * @return The jobId.
     */
    @java.lang.Override
    public long getJobId() {
      return jobId_;
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private volatile java.lang.Object code_;
    /**
     * <pre>
     * 执行代码
     * </pre>
     *
     * <code>string code = 2;</code>
     * @return The code.
     */
    @java.lang.Override
    public java.lang.String getCode() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        code_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 执行代码
     * </pre>
     *
     * <code>string code = 2;</code>
     * @return The bytes for code.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCodeBytes() {
      java.lang.Object ref = code_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        code_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (jobId_ != 0L) {
        output.writeInt64(1, jobId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, code_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (jobId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, jobId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, code_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest)) {
        return super.equals(obj);
      }
      com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest other = (com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest) obj;

      if (getJobId()
          != other.getJobId()) return false;
      if (!getCode()
          .equals(other.getCode())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + JOBID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getJobId());
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DataxServiceProto.RunRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DataxServiceProto.RunRequest)
        com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.internal_static_DataxServiceProto_RunRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.internal_static_DataxServiceProto_RunRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest.class, com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest.Builder.class);
      }

      // Construct using com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        jobId_ = 0L;

        code_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.internal_static_DataxServiceProto_RunRequest_descriptor;
      }

      @java.lang.Override
      public com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest getDefaultInstanceForType() {
        return com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest build() {
        com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest buildPartial() {
        com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest result = new com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest(this);
        result.jobId_ = jobId_;
        result.code_ = code_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest) {
          return mergeFrom((com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest other) {
        if (other == com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest.getDefaultInstance()) return this;
        if (other.getJobId() != 0L) {
          setJobId(other.getJobId());
        }
        if (!other.getCode().isEmpty()) {
          code_ = other.code_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long jobId_ ;
      /**
       * <pre>
       * 任务id
       * </pre>
       *
       * <code>int64 jobId = 1;</code>
       * @return The jobId.
       */
      @java.lang.Override
      public long getJobId() {
        return jobId_;
      }
      /**
       * <pre>
       * 任务id
       * </pre>
       *
       * <code>int64 jobId = 1;</code>
       * @param value The jobId to set.
       * @return This builder for chaining.
       */
      public Builder setJobId(long value) {
        
        jobId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 任务id
       * </pre>
       *
       * <code>int64 jobId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearJobId() {
        
        jobId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object code_ = "";
      /**
       * <pre>
       * 执行代码
       * </pre>
       *
       * <code>string code = 2;</code>
       * @return The code.
       */
      public java.lang.String getCode() {
        java.lang.Object ref = code_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          code_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 执行代码
       * </pre>
       *
       * <code>string code = 2;</code>
       * @return The bytes for code.
       */
      public com.google.protobuf.ByteString
          getCodeBytes() {
        java.lang.Object ref = code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 执行代码
       * </pre>
       *
       * <code>string code = 2;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 执行代码
       * </pre>
       *
       * <code>string code = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        
        code_ = getDefaultInstance().getCode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 执行代码
       * </pre>
       *
       * <code>string code = 2;</code>
       * @param value The bytes for code to set.
       * @return This builder for chaining.
       */
      public Builder setCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        code_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DataxServiceProto.RunRequest)
    }

    // @@protoc_insertion_point(class_scope:DataxServiceProto.RunRequest)
    private static final com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest();
    }

    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RunRequest>
        PARSER = new com.google.protobuf.AbstractParser<RunRequest>() {
      @java.lang.Override
      public RunRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RunRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RunRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RunRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RunResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DataxServiceProto.RunResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 任务id
     * </pre>
     *
     * <code>int64 jobId = 1;</code>
     * @return The jobId.
     */
    long getJobId();

    /**
     * <pre>
     * 任务唯一标识
     * </pre>
     *
     * <code>int64 uid = 2;</code>
     * @return The uid.
     */
    long getUid();

    /**
     * <pre>
     * 消息
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * 消息
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <pre>
     * 状态
     * </pre>
     *
     * <code>int32 status = 4;</code>
     * @return The status.
     */
    int getStatus();
  }
  /**
   * Protobuf type {@code DataxServiceProto.RunResponse}
   */
  public static final class RunResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DataxServiceProto.RunResponse)
      RunResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RunResponse.newBuilder() to construct.
    private RunResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RunResponse() {
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RunResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RunResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              jobId_ = input.readInt64();
              break;
            }
            case 16: {

              uid_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 32: {

              status_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.internal_static_DataxServiceProto_RunResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.internal_static_DataxServiceProto_RunResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse.class, com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse.Builder.class);
    }

    public static final int JOBID_FIELD_NUMBER = 1;
    private long jobId_;
    /**
     * <pre>
     * 任务id
     * </pre>
     *
     * <code>int64 jobId = 1;</code>
     * @return The jobId.
     */
    @java.lang.Override
    public long getJobId() {
      return jobId_;
    }

    public static final int UID_FIELD_NUMBER = 2;
    private long uid_;
    /**
     * <pre>
     * 任务唯一标识
     * </pre>
     *
     * <code>int64 uid = 2;</code>
     * @return The uid.
     */
    @java.lang.Override
    public long getUid() {
      return uid_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    private volatile java.lang.Object message_;
    /**
     * <pre>
     * 消息
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 消息
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private int status_;
    /**
     * <pre>
     * 状态
     * </pre>
     *
     * <code>int32 status = 4;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (jobId_ != 0L) {
        output.writeInt64(1, jobId_);
      }
      if (uid_ != 0L) {
        output.writeInt64(2, uid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
      }
      if (status_ != 0) {
        output.writeInt32(4, status_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (jobId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, jobId_);
      }
      if (uid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, uid_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse)) {
        return super.equals(obj);
      }
      com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse other = (com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse) obj;

      if (getJobId()
          != other.getJobId()) return false;
      if (getUid()
          != other.getUid()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (getStatus()
          != other.getStatus()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + JOBID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getJobId());
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUid());
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DataxServiceProto.RunResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DataxServiceProto.RunResponse)
        com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.internal_static_DataxServiceProto_RunResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.internal_static_DataxServiceProto_RunResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse.class, com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse.Builder.class);
      }

      // Construct using com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        jobId_ = 0L;

        uid_ = 0L;

        message_ = "";

        status_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.internal_static_DataxServiceProto_RunResponse_descriptor;
      }

      @java.lang.Override
      public com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse getDefaultInstanceForType() {
        return com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse build() {
        com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse buildPartial() {
        com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse result = new com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse(this);
        result.jobId_ = jobId_;
        result.uid_ = uid_;
        result.message_ = message_;
        result.status_ = status_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse) {
          return mergeFrom((com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse other) {
        if (other == com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse.getDefaultInstance()) return this;
        if (other.getJobId() != 0L) {
          setJobId(other.getJobId());
        }
        if (other.getUid() != 0L) {
          setUid(other.getUid());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long jobId_ ;
      /**
       * <pre>
       * 任务id
       * </pre>
       *
       * <code>int64 jobId = 1;</code>
       * @return The jobId.
       */
      @java.lang.Override
      public long getJobId() {
        return jobId_;
      }
      /**
       * <pre>
       * 任务id
       * </pre>
       *
       * <code>int64 jobId = 1;</code>
       * @param value The jobId to set.
       * @return This builder for chaining.
       */
      public Builder setJobId(long value) {
        
        jobId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 任务id
       * </pre>
       *
       * <code>int64 jobId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearJobId() {
        
        jobId_ = 0L;
        onChanged();
        return this;
      }

      private long uid_ ;
      /**
       * <pre>
       * 任务唯一标识
       * </pre>
       *
       * <code>int64 uid = 2;</code>
       * @return The uid.
       */
      @java.lang.Override
      public long getUid() {
        return uid_;
      }
      /**
       * <pre>
       * 任务唯一标识
       * </pre>
       *
       * <code>int64 uid = 2;</code>
       * @param value The uid to set.
       * @return This builder for chaining.
       */
      public Builder setUid(long value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 任务唯一标识
       * </pre>
       *
       * <code>int64 uid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUid() {
        
        uid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * 消息
       * </pre>
       *
       * <code>string message = 3;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 消息
       * </pre>
       *
       * <code>string message = 3;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息
       * </pre>
       *
       * <code>string message = 3;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息
       * </pre>
       *
       * <code>string message = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息
       * </pre>
       *
       * <code>string message = 3;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <pre>
       * 状态
       * </pre>
       *
       * <code>int32 status = 4;</code>
       * @return The status.
       */
      @java.lang.Override
      public int getStatus() {
        return status_;
      }
      /**
       * <pre>
       * 状态
       * </pre>
       *
       * <code>int32 status = 4;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 状态
       * </pre>
       *
       * <code>int32 status = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DataxServiceProto.RunResponse)
    }

    // @@protoc_insertion_point(class_scope:DataxServiceProto.RunResponse)
    private static final com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse();
    }

    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RunResponse>
        PARSER = new com.google.protobuf.AbstractParser<RunResponse>() {
      @java.lang.Override
      public RunResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RunResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RunResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RunResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.RunResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StopRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DataxServiceProto.StopRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 任务唯一标识
     * </pre>
     *
     * <code>int64 uid = 1;</code>
     * @return The uid.
     */
    long getUid();
  }
  /**
   * <pre>
   **
   * 给用户返回PID是否很危险
   * </pre>
   *
   * Protobuf type {@code DataxServiceProto.StopRequest}
   */
  public static final class StopRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DataxServiceProto.StopRequest)
      StopRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StopRequest.newBuilder() to construct.
    private StopRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StopRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StopRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StopRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              uid_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.internal_static_DataxServiceProto_StopRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.internal_static_DataxServiceProto_StopRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest.class, com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private long uid_;
    /**
     * <pre>
     * 任务唯一标识
     * </pre>
     *
     * <code>int64 uid = 1;</code>
     * @return The uid.
     */
    @java.lang.Override
    public long getUid() {
      return uid_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (uid_ != 0L) {
        output.writeInt64(1, uid_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (uid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, uid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest)) {
        return super.equals(obj);
      }
      com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest other = (com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest) obj;

      if (getUid()
          != other.getUid()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUid());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     * 给用户返回PID是否很危险
     * </pre>
     *
     * Protobuf type {@code DataxServiceProto.StopRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DataxServiceProto.StopRequest)
        com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.internal_static_DataxServiceProto_StopRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.internal_static_DataxServiceProto_StopRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest.class, com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest.Builder.class);
      }

      // Construct using com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uid_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.internal_static_DataxServiceProto_StopRequest_descriptor;
      }

      @java.lang.Override
      public com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest getDefaultInstanceForType() {
        return com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest build() {
        com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest buildPartial() {
        com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest result = new com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest(this);
        result.uid_ = uid_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest) {
          return mergeFrom((com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest other) {
        if (other == com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest.getDefaultInstance()) return this;
        if (other.getUid() != 0L) {
          setUid(other.getUid());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long uid_ ;
      /**
       * <pre>
       * 任务唯一标识
       * </pre>
       *
       * <code>int64 uid = 1;</code>
       * @return The uid.
       */
      @java.lang.Override
      public long getUid() {
        return uid_;
      }
      /**
       * <pre>
       * 任务唯一标识
       * </pre>
       *
       * <code>int64 uid = 1;</code>
       * @param value The uid to set.
       * @return This builder for chaining.
       */
      public Builder setUid(long value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 任务唯一标识
       * </pre>
       *
       * <code>int64 uid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUid() {
        
        uid_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DataxServiceProto.StopRequest)
    }

    // @@protoc_insertion_point(class_scope:DataxServiceProto.StopRequest)
    private static final com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest();
    }

    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StopRequest>
        PARSER = new com.google.protobuf.AbstractParser<StopRequest>() {
      @java.lang.Override
      public StopRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StopRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StopRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StopRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StopResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DataxServiceProto.StopResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 状态
     * </pre>
     *
     * <code>int64 uid = 1;</code>
     * @return The uid.
     */
    long getUid();

    /**
     * <pre>
     * 状态
     * </pre>
     *
     * <code>int32 status = 2;</code>
     * @return The status.
     */
    int getStatus();
  }
  /**
   * Protobuf type {@code DataxServiceProto.StopResponse}
   */
  public static final class StopResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DataxServiceProto.StopResponse)
      StopResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StopResponse.newBuilder() to construct.
    private StopResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StopResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StopResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StopResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              uid_ = input.readInt64();
              break;
            }
            case 16: {

              status_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.internal_static_DataxServiceProto_StopResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.internal_static_DataxServiceProto_StopResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse.class, com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private long uid_;
    /**
     * <pre>
     * 状态
     * </pre>
     *
     * <code>int64 uid = 1;</code>
     * @return The uid.
     */
    @java.lang.Override
    public long getUid() {
      return uid_;
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    /**
     * <pre>
     * 状态
     * </pre>
     *
     * <code>int32 status = 2;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (uid_ != 0L) {
        output.writeInt64(1, uid_);
      }
      if (status_ != 0) {
        output.writeInt32(2, status_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (uid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, uid_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse)) {
        return super.equals(obj);
      }
      com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse other = (com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse) obj;

      if (getUid()
          != other.getUid()) return false;
      if (getStatus()
          != other.getStatus()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUid());
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DataxServiceProto.StopResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DataxServiceProto.StopResponse)
        com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.internal_static_DataxServiceProto_StopResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.internal_static_DataxServiceProto_StopResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse.class, com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse.Builder.class);
      }

      // Construct using com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uid_ = 0L;

        status_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.internal_static_DataxServiceProto_StopResponse_descriptor;
      }

      @java.lang.Override
      public com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse getDefaultInstanceForType() {
        return com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse build() {
        com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse buildPartial() {
        com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse result = new com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse(this);
        result.uid_ = uid_;
        result.status_ = status_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse) {
          return mergeFrom((com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse other) {
        if (other == com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse.getDefaultInstance()) return this;
        if (other.getUid() != 0L) {
          setUid(other.getUid());
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long uid_ ;
      /**
       * <pre>
       * 状态
       * </pre>
       *
       * <code>int64 uid = 1;</code>
       * @return The uid.
       */
      @java.lang.Override
      public long getUid() {
        return uid_;
      }
      /**
       * <pre>
       * 状态
       * </pre>
       *
       * <code>int64 uid = 1;</code>
       * @param value The uid to set.
       * @return This builder for chaining.
       */
      public Builder setUid(long value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 状态
       * </pre>
       *
       * <code>int64 uid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUid() {
        
        uid_ = 0L;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <pre>
       * 状态
       * </pre>
       *
       * <code>int32 status = 2;</code>
       * @return The status.
       */
      @java.lang.Override
      public int getStatus() {
        return status_;
      }
      /**
       * <pre>
       * 状态
       * </pre>
       *
       * <code>int32 status = 2;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 状态
       * </pre>
       *
       * <code>int32 status = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DataxServiceProto.StopResponse)
    }

    // @@protoc_insertion_point(class_scope:DataxServiceProto.StopResponse)
    private static final com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse();
    }

    public static com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StopResponse>
        PARSER = new com.google.protobuf.AbstractParser<StopResponse>() {
      @java.lang.Override
      public StopResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StopResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StopResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StopResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.wallfacers.data.platform.stub.service.datax.DataxServiceBuilder.StopResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataxServiceProto_RunRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataxServiceProto_RunRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataxServiceProto_RunResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataxServiceProto_RunResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataxServiceProto_StopRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataxServiceProto_StopRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataxServiceProto_StopResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataxServiceProto_StopResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022DataxService.proto\022\021DataxServiceProto\"" +
      ")\n\nRunRequest\022\r\n\005jobId\030\001 \001(\003\022\014\n\004code\030\002 \001" +
      "(\t\"J\n\013RunResponse\022\r\n\005jobId\030\001 \001(\003\022\013\n\003uid\030" +
      "\002 \001(\003\022\017\n\007message\030\003 \001(\t\022\016\n\006status\030\004 \001(\005\"\032" +
      "\n\013StopRequest\022\013\n\003uid\030\001 \001(\003\"+\n\014StopRespon" +
      "se\022\013\n\003uid\030\001 \001(\003\022\016\n\006status\030\002 \001(\0052\243\001\n\014Data" +
      "xService\022H\n\003run\022\035.DataxServiceProto.RunR" +
      "equest\032\036.DataxServiceProto.RunResponse\"\000" +
      "0\001\022I\n\004stop\022\036.DataxServiceProto.StopReque" +
      "st\032\037.DataxServiceProto.StopResponse\"\000BN\n" +
      "/com.wallfacers.data.platform.stub.servi" +
      "ce.dataxB\023DataxServiceBuilderP\000\242\002\003HLWb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DataxServiceProto_RunRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DataxServiceProto_RunRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataxServiceProto_RunRequest_descriptor,
        new java.lang.String[] { "JobId", "Code", });
    internal_static_DataxServiceProto_RunResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DataxServiceProto_RunResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataxServiceProto_RunResponse_descriptor,
        new java.lang.String[] { "JobId", "Uid", "Message", "Status", });
    internal_static_DataxServiceProto_StopRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_DataxServiceProto_StopRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataxServiceProto_StopRequest_descriptor,
        new java.lang.String[] { "Uid", });
    internal_static_DataxServiceProto_StopResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_DataxServiceProto_StopResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataxServiceProto_StopResponse_descriptor,
        new java.lang.String[] { "Uid", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
